<?php
/**
 * Created by PhpStorm.
 * User: Костя
 * Date: 23.09.2018
 * Time: 16:40
 */

namespace App\Controllers;

use App\Core\Controller;
use App\Core\View;
use application\core\ModelList;

class ControllerList extends Controller
{
    function __construct()
    {
        parent::__construct();
        $this->model = new ModelList();
        $this->view = new View();
    }

    function actionIndex()
    {
        parent::actionIndex(); // TODO: Change the autogenerated stub
    }
}